### ISSUE TITLE
Fix Open Graph tags on Wiki pages

### ISSUE THREAD

**Issue by davorg** [Act-Conferences/tpc-2018-glasgow#33]
The code we're using to get the URL for the OG tags ignores request parameters. I think the Wiki is the only section of the site that uses parameters.

**Comment by TBSliver** [comment]
Hmm is the OG code hand spun or pre-generated? If you need query params we can always throw [URI.js](https://medialize.github.io/URI.js/) at the problem to get it if its easy to modify the code (not sure where to look for the OG code heh)

**Comment by davorg** [comment]
It's hand-spun. The bit in the `ui` template that currently generates it looks like this:

    <meta property="og:url" content="[% global.request.base_url %][% global.request.r.uri %]" />

I just need to work out the correct incantation to get the arguments out of the `global.request.r` object. The fact that it's mod_perl 1 doesn't help :-)
