### ISSUE TITLE
Reconsider the Workshops page

### ISSUE THREAD

**Issue by davorg** [Act-Conferences/tpc-2018-glasgow#36]
It was useful a week ago, but now all of that information is in the schedule

**Comment by TBSliver** [comment]
The info is there, but having a 'these specifically are the workshops' rather than working out that from the schedule is probably easier for people - less clicking through the schedule to get to the 'what the hell are these workshops about'

**Comment by davorg** [comment]
Seems pointless caring about this two years after the conference :-)
