### ISSUE TITLE
Tom's Redesign

### ISSUE THREAD

**Issue by davorg** [Act-Conferences/tpc-2018-glasgow#43]

**Comment by TBSliver** [comment]
Plans!

![Browser View](https://tbsliver.me/wp-content/uploads/2018/06/Mobile-View.png)

![Mobile View](https://tbsliver.me/wp-content/uploads/2018/06/Mobile-View.png)

**Comment by TBSliver** [comment]
Pull request #49 is in for it, if you want to see the redesign before it gets merged, see here: http://test.mongueurs.net/tpc-2018-glasgow/
